version: '2'
services:
    bind:
        image: sameersbn/bind:9.9.5-20170129
        container_name: bind
        restart: on-failure # other option: always - if you want persistent through host reboots
        ports:
            - '53:53'
            - '53:53/udp'
            - '10000:10000/tcp'
        volumes:
            - './bind:/data'
        stdin_open: true 
        tty: true
